reflect CLI options on web URL
FlamingTempura/bibtex-tidy pull request #344
Opened 2022-10-01 02:55 UTC by thisiscam

Attempt at #50 .

Currently serializes CLI options with JSON, which is totally unreadable.

2022-10-01 10:45 UTC, FlamingTempura requested changes
Thanks for the PR!

The only thing I'd like changed is to call the query param `opt` instead of `cli` (since it's not really options specific to the command line).

Other than that, good to go! Really appreciate you working on this feature (I don't find much time to maintain this library).

I'll make the merge when this change is made.

2022-10-01 10:45 UTC, FlamingTempura commented on docs/index.ts
> +	const options_json = urlParams.get('cli');
```suggestion
	const options_json = urlParams.get('opt');
```

2022-10-01 10:45 UTC, FlamingTempura commented on docs/index.ts
> +	window.history.pushState(options, "", `index.html?cli=${encodeURIComponent(options_json)}`);
```suggestion
	window.history.pushState(options, "", `index.html?opt=${encodeURIComponent(options_json)}`);
```

2022-10-01 16:08 UTC, thisiscam commented on docs/index.ts
> +	window.history.pushState(options, "", `index.html?cli=${encodeURIComponent(options_json)}`);
Fixed in the new commit. Thanks!

2022-10-01 16:10 UTC, thisiscam commented
@FlamingTempura I implemented your suggestion and added a delay to textarea inputs, to avoid accumulating a browser history time frame for each character one type.

2022-10-02 14:28 UTC, merged

2022-10-02 14:29 UTC, FlamingTempura commented
Merged, thanks for your contribution